default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: plant_generator_microservice_development

test:
  <<: *default
  database: plant_generator_microservice_test

production:
  <<: *default
  database: plant_generator_microservice_production
  username: plant_generator_microservice
  password: <%= ENV['bloombrothers'] %>